// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMeKet72wCJeEXIMlSP3y50bAPKpe5OQ8',
    appId: '1:397729294479:web:5e83d88f3c2b997898a8fa',
    messagingSenderId: '397729294479',
    projectId: 'autibuddy-b2f45',
    authDomain: 'autibuddy-b2f45.firebaseapp.com',
    storageBucket: 'autibuddy-b2f45.firebasestorage.app',
    measurementId: 'G-KZEL4CS95E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBehYKn5Ni4bC7v5sn-e44FDE_EzoUOHsE',
    appId: '1:397729294479:android:e2fc398fd27ecd6f98a8fa',
    messagingSenderId: '397729294479',
    projectId: 'autibuddy-b2f45',
    storageBucket: 'autibuddy-b2f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCirjjEG6PxV8Jw6ZmmnRjA2V7Zrl-pxR4',
    appId: '1:397729294479:ios:c8a45ef63e1c962398a8fa',
    messagingSenderId: '397729294479',
    projectId: 'autibuddy-b2f45',
    storageBucket: 'autibuddy-b2f45.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCirjjEG6PxV8Jw6ZmmnRjA2V7Zrl-pxR4',
    appId: '1:397729294479:ios:c8a45ef63e1c962398a8fa',
    messagingSenderId: '397729294479',
    projectId: 'autibuddy-b2f45',
    storageBucket: 'autibuddy-b2f45.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMeKet72wCJeEXIMlSP3y50bAPKpe5OQ8',
    appId: '1:397729294479:web:ba27653ec141c3cd98a8fa',
    messagingSenderId: '397729294479',
    projectId: 'autibuddy-b2f45',
    authDomain: 'autibuddy-b2f45.firebaseapp.com',
    storageBucket: 'autibuddy-b2f45.firebasestorage.app',
    measurementId: 'G-G98M7GPTJD',
  );
}
